In [2]:
import pandas as pd

In [6]:
# df containging all zip
df = pd.read_csv("311_Service_Requests_2020.csv")
df.head()

/Users/eugenepaik/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (20,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,45285347,01/01/2020 12:00:00 AM,01/10/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11229.0,3442 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.600129,-73.941843,"(40.6001292057807, -73.94184291675883)"
1,45285651,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,10458.0,2701 DECATUR AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.864866,-73.888783,"(40.86486556770799, -73.88878325729915)"
2,45285821,01/01/2020 12:00:00 AM,01/02/2020 09:50:09 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Other (Explain Below),11203.0,5707 CHURCH AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.652536,-73.923540,"(40.65253575905768, -73.92353994017134)"
3,45287907,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11214.0,1602 SHORE PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.595653,-74.000173,"(40.59565343138651, -74.00017283917487)"
4,45288240,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,11385.0,1717 CORNELIA STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700366,-73.905438,"(40.700366489799876, -73.90543829006366)"

In [7]:
# df2 is a subset of df, containing rows that include zip 10001
df2 = df[df["Incident Zip"] == 10001.0]
df2.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
1506,45285919,01/01/2020 08:09:00 AM,01/01/2020 05:50:00 PM,DEP,Department of Environmental Protection,Water System,Hydrant Leaking (WC1),NaN,10001.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.749103,-73.992006,"(40.74910254075324, -73.99200582083958)"
1787,45288507,01/01/2020 10:01:28 AM,01/01/2020 10:11:54 AM,DHS,Department of Homeless Services,Homeless Person Assistance,NaN,NaN,10001.0,7 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.750991,-73.990623,"(40.75099082290243, -73.99062326583427)"
2355,45286809,01/01/2020 12:56:08 PM,01/01/2020 01:03:05 PM,DHS,Department of Homeless Services,Homeless Person Assistance,NaN,NaN,10001.0,294 10 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.750297,-74.002256,"(40.750296761372525, -74.00225573432823)"
2479,45285011,01/01/2020 01:29:18 PM,01/01/2020 02:54:52 PM,NYPD,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,Street/Sidewalk,10001.0,44 WEST 34 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.749322,-73.986682,"(40.74932162810357, -73.98668233941905)"
2482,45288930,01/01/2020 01:30:35 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,NaN,10001.0,44 WEST 34 STREET,...,NaN,NaN,"44 WEST 34 STREET, MANHATTAN (NEW YORK), NY,...",NaN,NaN,NaN,NaN,40.749322,-73.986682,"(40.74932162810357, -73.98668233941905)"

In [8]:
complaints = list(df2["Complaint Type"])
total_counts = 0
parking_counts = 0

for i in complaints:
    if i == "Illegal Parking":
        parking_counts += 1
    total_counts += 1 

print("total counts:", total_counts)
print("parking counts:", parking_counts)

total counts: 11617
parking counts: 619

In [9]:
my_zip_proportion = (parking_counts / total_counts) * 100
print(my_zip_proportion)

5.328398037359043

In [10]:
total_complaints = list(df["Complaint Type"])
total_zip_counts = 0
total_parking_counts = 0

for i in total_complaints:
    if i == "Illegal Parking":
        total_parking_counts += 1
    total_zip_counts += 1 

print("total zip counts:", total_zip_counts)
print("total parking counts:", total_parking_counts)

total zip counts: 2587316
total parking counts: 193721

In [11]:
total_zip_proportion = (total_parking_counts / total_zip_counts) * 100
print(total_zip_proportion)

7.4873343650331075

In [12]:
higher_parking_proportion = my_zip_proportion > total_zip_proportion
print(higher_parking_proportion)

False